//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public Nullable<System.Guid> ASSIGNED_USER_ID { get; set; }
        public Nullable<System.Guid> TEAM_ID { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string NAME { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public Nullable<System.Guid> PARENT_ID { get; set; }
        public string INDUSTRY { get; set; }
        public string ANNUAL_REVENUE { get; set; }
        public string PHONE_FAX { get; set; }
        public string BILLING_ADDRESS_STREET { get; set; }
        public string BILLING_ADDRESS_CITY { get; set; }
        public string BILLING_ADDRESS_STATE { get; set; }
        public string BILLING_ADDRESS_POSTALCODE { get; set; }
        public string BILLING_ADDRESS_COUNTRY { get; set; }
        public string DESCRIPTION { get; set; }
        public string RATING { get; set; }
        public string PHONE_OFFICE { get; set; }
        public string PHONE_ALTERNATE { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string WEBSITE { get; set; }
        public string OWNERSHIP { get; set; }
        public string EMPLOYEES { get; set; }
        public string TICKER_SYMBOL { get; set; }
        public string SIC_CODE { get; set; }
        public string SHIPPING_ADDRESS_STREET { get; set; }
        public string SHIPPING_ADDRESS_CITY { get; set; }
        public string SHIPPING_ADDRESS_STATE { get; set; }
        public string SHIPPING_ADDRESS_POSTALCODE { get; set; }
        public string SHIPPING_ADDRESS_COUNTRY { get; set; }
        public Nullable<System.Guid> CAMPAIGN_ID { get; set; }
        public Nullable<System.Guid> TEAM_SET_ID { get; set; }
    }
}
