//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public Nullable<System.Guid> ASSIGNED_USER_ID { get; set; }
        public Nullable<System.Guid> TEAM_ID { get; set; }
        public string SALUTATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string LEAD_SOURCE { get; set; }
        public string TITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<System.Guid> REPORTS_TO_ID { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<bool> DO_NOT_CALL { get; set; }
        public string PHONE_HOME { get; set; }
        public string PHONE_MOBILE { get; set; }
        public string PHONE_WORK { get; set; }
        public string PHONE_OTHER { get; set; }
        public string PHONE_FAX { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string ASSISTANT { get; set; }
        public string ASSISTANT_PHONE { get; set; }
        public Nullable<bool> EMAIL_OPT_OUT { get; set; }
        public Nullable<bool> INVALID_EMAIL { get; set; }
        public string SMS_OPT_IN { get; set; }
        public string TWITTER_SCREEN_NAME { get; set; }
        public string PRIMARY_ADDRESS_STREET { get; set; }
        public string PRIMARY_ADDRESS_CITY { get; set; }
        public string PRIMARY_ADDRESS_STATE { get; set; }
        public string PRIMARY_ADDRESS_POSTALCODE { get; set; }
        public string PRIMARY_ADDRESS_COUNTRY { get; set; }
        public string ALT_ADDRESS_STREET { get; set; }
        public string ALT_ADDRESS_CITY { get; set; }
        public string ALT_ADDRESS_STATE { get; set; }
        public string ALT_ADDRESS_POSTALCODE { get; set; }
        public string ALT_ADDRESS_COUNTRY { get; set; }
        public string DESCRIPTION { get; set; }
        public string PORTAL_NAME { get; set; }
        public string PORTAL_PASSWORD { get; set; }
        public Nullable<bool> PORTAL_ACTIVE { get; set; }
        public string PORTAL_APP { get; set; }
        public Nullable<System.Guid> CAMPAIGN_ID { get; set; }
        public Nullable<System.Guid> TEAM_SET_ID { get; set; }
    }
}
