//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public Nullable<System.Guid> ASSIGNED_USER_ID { get; set; }
        public Nullable<System.Guid> TEAM_ID { get; set; }
        public string DOCUMENT_NAME { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATE { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY_ID { get; set; }
        public string SUBCATEGORY_ID { get; set; }
        public string STATUS_ID { get; set; }
        public Nullable<System.Guid> DOCUMENT_REVISION_ID { get; set; }
        public Nullable<bool> MAIL_MERGE_DOCUMENT { get; set; }
        public Nullable<System.Guid> RELATED_DOC_ID { get; set; }
        public Nullable<System.Guid> RELATED_DOC_REV_ID { get; set; }
        public Nullable<bool> IS_TEMPLATE { get; set; }
        public string TEMPLATE_TYPE { get; set; }
        public string PRIMARY_MODULE { get; set; }
        public string SECONDARY_MODULE { get; set; }
        public Nullable<System.Guid> TEAM_SET_ID { get; set; }
    }
}
