//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_TEMPLATES
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public Nullable<System.Guid> ASSIGNED_USER_ID { get; set; }
        public Nullable<System.Guid> TEAM_ID { get; set; }
        public Nullable<bool> PUBLISHED { get; set; }
        public Nullable<bool> READ_ONLY { get; set; }
        public Nullable<bool> TEXT_ONLY { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public string BODY_HTML { get; set; }
        public Nullable<System.Guid> TEAM_SET_ID { get; set; }
    }
}
