//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPACCRMEntities : DbContext
    {
        public IPACCRMEntities()
            : base("name=IPACCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public virtual DbSet<ACL_ROLES> ACL_ROLES { get; set; }
        public virtual DbSet<CAMPAIGN> CAMPAIGNS { get; set; }
        public virtual DbSet<Case> CASES { get; set; }
        public virtual DbSet<CONTACT> CONTACTS { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENTS { get; set; }
        public virtual DbSet<EMAIL_TEMPLATES> EMAIL_TEMPLATES { get; set; }
        public virtual DbSet<EMAIL> EMAILS { get; set; }
        public virtual DbSet<LEAD> LEADS { get; set; }
        public virtual DbSet<MEETING> MEETINGS { get; set; }
        public virtual DbSet<NOTE> NOTES { get; set; }
        public virtual DbSet<PROJECT> PROJECTs { get; set; }
        public virtual DbSet<TASK> TASKS { get; set; }
        public virtual DbSet<TEAM> TEAMS { get; set; }
        public virtual DbSet<Test_Table> Test_Table { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
