//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETING
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public Nullable<System.Guid> ASSIGNED_USER_ID { get; set; }
        public Nullable<System.Guid> TEAM_ID { get; set; }
        public string NAME { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> DURATION_HOURS { get; set; }
        public Nullable<int> DURATION_MINUTES { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> TIME_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public string STATUS { get; set; }
        public string PARENT_TYPE { get; set; }
        public Nullable<System.Guid> PARENT_ID { get; set; }
        public Nullable<int> REMINDER_TIME { get; set; }
        public string DESCRIPTION { get; set; }
        public string OUTLOOK_ID { get; set; }
        public Nullable<System.Guid> TEAM_SET_ID { get; set; }
        public Nullable<int> EMAIL_REMINDER_TIME { get; set; }
        public Nullable<int> SMS_REMINDER_TIME { get; set; }
        public string REPEAT_TYPE { get; set; }
        public Nullable<int> REPEAT_INTERVAL { get; set; }
        public string REPEAT_DOW { get; set; }
        public Nullable<System.DateTime> REPEAT_UNTIL { get; set; }
        public Nullable<int> REPEAT_COUNT { get; set; }
        public Nullable<System.Guid> REPEAT_PARENT_ID { get; set; }
        public string RECURRING_SOURCE { get; set; }
        public Nullable<bool> ALL_DAY_EVENT { get; set; }
    }
}
