//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public Nullable<System.Guid> ASSIGNED_USER_ID { get; set; }
        public Nullable<System.Guid> TEAM_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> ESTIMATED_START_DATE { get; set; }
        public Nullable<System.DateTime> ESTIMATED_END_DATE { get; set; }
        public string STATUS { get; set; }
        public string PRIORITY { get; set; }
        public Nullable<bool> IS_TEMPLATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.Guid> TEAM_SET_ID { get; set; }
    }
}
