//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Table
    {
        public int SLID { get; set; }
        public int Year { get; set; }
        public int Elec { get; set; }
        public int Book { get; set; }
        public int Home { get; set; }
    }
}
