//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPAC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public System.Guid ID { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.Guid> CREATED_BY { get; set; }
        public System.DateTime DATE_ENTERED { get; set; }
        public Nullable<System.Guid> MODIFIED_USER_ID { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED_UTC { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_HASH { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.Guid> REPORTS_TO_ID { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public Nullable<bool> IS_ADMIN_DELEGATE { get; set; }
        public Nullable<bool> RECEIVE_NOTIFICATIONS { get; set; }
        public string DESCRIPTION { get; set; }
        public string TITLE { get; set; }
        public string DEPARTMENT { get; set; }
        public string PHONE_HOME { get; set; }
        public string PHONE_MOBILE { get; set; }
        public string PHONE_WORK { get; set; }
        public string PHONE_OTHER { get; set; }
        public string PHONE_FAX { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string STATUS { get; set; }
        public string ADDRESS_STREET { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_STATE { get; set; }
        public string ADDRESS_COUNTRY { get; set; }
        public string ADDRESS_POSTALCODE { get; set; }
        public string USER_PREFERENCES { get; set; }
        public Nullable<bool> PORTAL_ONLY { get; set; }
        public string EMPLOYEE_STATUS { get; set; }
        public string MESSENGER_ID { get; set; }
        public string MESSENGER_TYPE { get; set; }
        public Nullable<bool> IS_GROUP { get; set; }
        public Nullable<System.Guid> DEFAULT_TEAM { get; set; }
        public Nullable<bool> SYSTEM_GENERATED_PASSWORD { get; set; }
        public Nullable<System.DateTime> PWD_LAST_CHANGED { get; set; }
        public string MAIL_SMTPUSER { get; set; }
        public string MAIL_SMTPPASS { get; set; }
        public Nullable<bool> GOOGLEAPPS_SYNC_CONTACTS { get; set; }
        public Nullable<bool> GOOGLEAPPS_SYNC_CALENDAR { get; set; }
        public string GOOGLEAPPS_USERNAME { get; set; }
        public string GOOGLEAPPS_PASSWORD { get; set; }
        public string FACEBOOK_ID { get; set; }
        public Nullable<bool> ICLOUD_SYNC_CONTACTS { get; set; }
        public Nullable<bool> ICLOUD_SYNC_CALENDAR { get; set; }
        public string ICLOUD_USERNAME { get; set; }
        public string ICLOUD_PASSWORD { get; set; }
        public string ICLOUD_CTAG_CONTACTS { get; set; }
        public string ICLOUD_CTAG_CALENDAR { get; set; }
        public string THEME { get; set; }
        public string DATE_FORMAT { get; set; }
        public string TIME_FORMAT { get; set; }
        public string LANG { get; set; }
        public Nullable<System.Guid> CURRENCY_ID { get; set; }
        public Nullable<System.Guid> TIMEZONE_ID { get; set; }
        public Nullable<bool> SAVE_QUERY { get; set; }
        public Nullable<bool> GROUP_TABS { get; set; }
        public Nullable<bool> SUBPANEL_TABS { get; set; }
        public string EXTENSION { get; set; }
        public string SMS_OPT_IN { get; set; }
    }
}
